# Generated by Django 4.2.29 on 2026-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0002_alter_activity_id_alter_dailystats_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystats",
            name="sleep_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="sleep_quality",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="dailystats",
            name="sleep_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailystats",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="socialgroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
