# Generated by Django 4.2.29 on 2026-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0003_dailystats_sleep_end_dailystats_sleep_quality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystats",
            name="date",
            field=models.DateField(),
        ),
    ]
